### ISSUE TITLE
install all the things 

### ISSUE THREAD

**Issue by nehamoopen** [kimbergmans/culinary-pilgrimage#1]
**Huiswerk #2** 😄 

- [x] Install R from the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/)

R is the programming language itself. It will be installed on your computer system but you can't use it directly (not easily, anyway).

- [x] Install RStudio from the [RStudio website](https://www.rstudio.com/products/rstudio/download/)

RStudio is an _Integrated Development Environment_ (IDE). This is the program we can use to write and run code R code. 

- [x] Install Git from [git-scm.com](https://git-scm.com/)

Git is software for version control that needs to be installed on your computer system. At a later point, we'll link your local Git installation to your user account on GitHub. 

- [x] All done, yay!

**Comment by kimbergmans** [comment]
I need to postpone the Huiswerk nummer 2, have had no time at all...
