### ISSUE TITLE
intro first page

### ISSUE THREAD

**Issue by kimbergmans** [kimbergmans/culinary-pilgrimage#4]
Dear visitor, 

This website was created by employees at the Utrecht University Library as a parting gift for colleague Coen Wilders. 
It consists of personal suggestions of restaurants and a certain dish, mostly in the Netherlands. 
As big believers in open science we created it as an open website, to be used by everyone. So enjoy! 

On behalf of the library, and with big bows to Neha Moopen (@nehamoopen) and Ruben Schalk (@RubenSchalk) who did all the coding,

Kim Bergmans

**Comment by kimbergmans** [comment]
Extra: 

To use the website, you can just click on the points on the map or use the menu on the left.

**Comment by nehamoopen** [comment]
done!
